# Generated by Django 4.0.4 on 2022-07-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=255)),
                ('todo_date', models.DateField()),
            ],
            options={
                'ordering': ['todo_date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('address', models.CharField(blank=True, max_length=70)),
                ('date_of_birth', models.DateField(blank=True)),
                ('phone', models.IntegerField()),
                ('todos', models.ManyToManyField(to='mytodo.todoitem')),
            ],
        ),
    ]
